/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyResultsRouteImport } from './routes/survey-results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIdRouteImport } from './routes/customer.$id'

const SurveyResultsRoute = SurveyResultsRouteImport.update({
  id: '/survey-results',
  path: '/survey-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIdRoute = CustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/survey-results': typeof SurveyResultsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/survey-results': typeof SurveyResultsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/survey-results': typeof SurveyResultsRoute
  '/customer/$id': typeof CustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/feedback'
    | '/home'
    | '/loyalty'
    | '/profile'
    | '/survey-results'
    | '/customer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/feedback'
    | '/home'
    | '/loyalty'
    | '/profile'
    | '/survey-results'
    | '/customer/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/feedback'
    | '/home'
    | '/loyalty'
    | '/profile'
    | '/survey-results'
    | '/customer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FeedbackRoute: typeof FeedbackRoute
  HomeRoute: typeof HomeRoute
  LoyaltyRoute: typeof LoyaltyRoute
  ProfileRoute: typeof ProfileRoute
  SurveyResultsRoute: typeof SurveyResultsRoute
  CustomerIdRoute: typeof CustomerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey-results': {
      id: '/survey-results'
      path: '/survey-results'
      fullPath: '/survey-results'
      preLoaderRoute: typeof SurveyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$id': {
      id: '/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  FeedbackRoute: FeedbackRoute,
  HomeRoute: HomeRoute,
  LoyaltyRoute: LoyaltyRoute,
  ProfileRoute: ProfileRoute,
  SurveyResultsRoute: SurveyResultsRoute,
  CustomerIdRoute: CustomerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
